from unidecode import unidecode
algo = str(input("Digite algo aqui: ")).strip().upper().lower()
tsa = unidecode(algo)
print("Iremos agora analisar o seu texto mais detalhadamente.")
print(f"A quantidade de caracteres é de {len(tsa)}")
print(f"A letra A aparece {tsa.count('a')} vez(es).")
print(f"A letra E aparece {tsa.count('e')} vez(es).")
print(f"A letra I aparece {tsa.count('i')} vez(es).")
print(f"A letra O aparece {tsa.count('o')} vez(es).")
print(f"A letra U aparece {tsa.count('u')} vez(es).")
print(f"A letra A aparece pela primeira vez na posição {tsa.find('a')+1}.")
print(f"A letra A aparece pela última vez na posição {tsa.rfind('a')+1}.")
print(f"A letra E aparece pela primeira vez na posição {tsa.find('e')+1}.")
print(f"A letra E aparece pela última vez na posição {tsa.rfind('e')+1}.")
print(f"A letra I aparece pela primeira vez na posição {tsa.find('i')+1}.")
print(f"A letra I aparece pela última vez na posição {tsa.rfind('i')+1}.")
print(f"A letra O aparece pela primeira vez na posição {tsa.find('o')+1}.")
print(f"A letra O aparece pela última vez na posição {tsa.rfind('o')+1}.")
print(f"A letra U aparece pela primeira vez na posição {tsa.find('u')+1}.")
print(f"A letra U aparece pela última vez na posição {tsa.rfind('u')+1}.")
